### ISSUE TITLE
Example for maybe extractor

### ISSUE THREAD

**Issue by razzeee** [billperegoy/elm-sifter#16]
Can you give me a hint how to make a extractor work on a Maybe value?

**Comment by billperegoy** [comment]
An extractor is just a function that takes a record and returns an element from it. So the `.name` extractor represents the lambda: `(\elem -> elem.name)`

So you could write a function that did something like:

`(\elem -> Maybe.withDefault elem "default value")`

I'm not sure if that's exactly what you were asking, so let me know if it wasn't. It's been a while since I wrote this code so I may understand your intention.

**Comment by razzeee** [comment]
I was able to work it out. I suspected I already get the value and not the parent element, which obviously was a wrong assumption :)

Thank you.

Is there any way to match against two values like this?
a => "firstname lastname"
b => "City With Multiple Words"

search string => "Words lastname"

If I do that with an and I don't get results and if I do an or I will get other persons having the city.
